name: "Install latest LXD"
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

    - name: Setup LXD
      uses: canonical/setup-lxd@[version]
      with:
        channel: latest/edge

    - name: Launch container
      run: |
        lxc launch ubuntu:24.04 u1
