name: CI
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: 📦 `docker build`
        run: |
          echo ::group::Stage: source
          docker build --target source
          echo ::endgroup::

          echo ::group::Stage: configure
          docker build --target configure
          echo ::endgroup::

          echo ::group::Stage: make
          docker build --target make
          echo ::endgroup::

          echo ::group::Stage: make-install
          docker build --target make-install
          echo ::endgroup::
