name: CI
on: 
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # minimal
            type=schedule
            # default
            type=schedule,pattern=nightly
            # handlebars
            type=schedule,pattern={{date 'YYYYMMDD'}}
            # handlebars with timezone
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}
            # minimal
            type=semver,pattern={{version}}
            # use custom value instead of git tag
            type=semver,pattern={{version}},value=v1.0.0
            # minimal
            type=pep440,pattern={{version}}
            # use custom value instead of git tag
            type=pep440,pattern={{version}},value=1.0.0
            # minimal
            type=match,pattern=\d.\d.\d
            # define match group
            type=match,pattern=v(.*),group=1
            # use custom value instead of git tag
            type=match,pattern=v(.*),group=1,value=v1.0.0
            # minimal
            type=edge
            # define default branch
            type=edge,branch=main
            # branch event
            type=ref,event=branch
            # tag event
            type=ref,event=tag
            # pull request event
            type=ref,event=pr
            type=raw,value=foo
            type=raw,value=bar
            # or
            type=raw,foo
            type=raw,bar
            # or
            foo
            bar
            # minimal (short sha)
            type=sha
            # full length sha
            type=sha,format=long
