name: CI

on: 
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        first-name:
          - Alice
          - Bob
          - Charlie
    outputs:
      Alice: ${{ steps.gen_output.outputs.Alice }}
      Bob: ${{ steps.gen_output.outputs.Bob }}
      Charlie: ${{ steps.gen_output.outputs.Charlie }}
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: dangling

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: build
          build-args: |
            FIRST_NAME=${{ matrix.first-name }}

      - name: Generate output
        id: gen_output
        run: |
          echo "${MATRIX_VALUE}=${TAGS%:dangling}@${DIGEST}" | tee -a "$GITHUB_OUTPUT"
        env:
          MATRIX_VALUE: ${{ matrix.first-name }}
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.push.outputs.digest }}

  combine:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: combine
          build-args: |
            INTERMEDIATE_IMAGE_ALICE=${{ needs.build.outputs.Alice }}
            INTERMEDIATE_IMAGE_BOB=${{ needs.build.outputs.Bob }}
            INTERMEDIATE_IMAGE_CHARLIE=${{ needs.build.outputs.Charlie }}
