name: CI
on: 
  push:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: ${{ github.ref_name }}

      - id: split
        run: |
          echo "imageName=${IMAGE_REFERENCE%%:*}" | tee -a "$GITHUB_OUTPUT"
          echo "imageTag=${IMAGE_REFERENCE##*:}" | tee -a "$GITHUB_OUTPUT"
        env:
          IMAGE_REFERENCE: ${{ steps.meta.outputs.tags }}

      - uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ steps.split.outputs.imageName }}
          imageTag: ${{ steps.split.outputs.imageTag }}
          push: always
