name: CI
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-15-intel
          - macos-15
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          import platform
          print(platform.uname())
      - shell: python
        run: |
          import platform
          print(platform.libc_ver())
