name: CI
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - run: "false"
      - run: echo allways
        if: always()
      - run: echo after
