name: CI
on: 
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            latest

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        id: digest
        run: echo "image_name=${TAGS%:latest}@${DIGEST}" | tee -a "$GITHUB_OUTPUT"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}

      - run: |
          set +e
          docker pull "$DIGEST_IMAGE_NAME"
          docker inspect "$DIGEST_IMAGE_NAME"
        env:
          DIGEST_IMAGE_NAME: ${{ steps.digest.outputs.image_name }}
