name: CI
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ github.repository }}

      - uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ steps.meta.outputs.tags }}
          push: always
